---
- name: DEB debian update repos
  block:
  - name: Update all repos and cache
    apt:
      update_cache: yes
      force_apt_get: yes
    changed_when: 0 # does not count as change

# INCLUDES
- name: DEB debian necessary packages
  include_tasks: install_packages.yml

- name: Import tasks to disable consistent device naming
  include_tasks: disable_consistent_device_naming.yml
  when: not 'lxc' in group_names # and not 'vm' in group_names

- name: Import bashrc
  include_tasks: bashrc.yml
