
- name: PVE nag box
  block:
  - name: Enable nag-box service
    service:
      name: pve_nag_box.service
      enabled: yes
      state: started

# disable zfs-event daemon since it is for vms/bare metal machines and keeps crashing
- name: Disable and stop zfs-zed.service
  service:
    name: zfs-zed
    enabled: no
    state: stopped
  when: "'lxc' in group_names"
